services:
  - type: web
    name: secure-proxy
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RUST_LOG
        value: info
    numInstances: 1
